services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - podcastnetwork

  app:
    build: .
    container_name: podcast_app
    command: uvicorn main:app --host 0.0.0.0 --port 8006 --reload 
    ports:
      - 8006:8006
    volumes:
      - .:/code/
    depends_on:
      - mongodb
    networks:
      - podcastnetwork
    links:
      - "authorizaton:authorizaton-app"

networks:
  podcastnetwork:
    name: podcastnetwork


volumes:
  dbdata6:
